http:
  listenAddr: ":8080"

release:
  releaseVersion: "@RELEASE_VERSION@1.2"
  releaseTime: "@RELEASE_TIME@1.2"


database:
  url: root:root@/mqtt?charset=utf8&parseTime=True&loc=Local
  maxIdle: 50
  maxActive: 100
  logMode: true
